services:
  industrial-ai:
    build: .
    image: industrial-ai_api:latest
    container_name: industrial_ai_container
    ports:
      - "3000:3000"
    restart: always
    environment:
       - APP_ENV=production




